server:
  port: 8082
  
spring:
  datasource:
    url: jdbc:h2:file:./data/appointmentDataBase
    username: root
    password: root
    driverClassName: org.h2.Driver
   
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    generate-ddl: true
    hibernate:
      ddl-auto: update

  h2:
    console.enabled: true
    console.path: /h2-console
    console.settings.trace: false 
    console.settings.web-allow-others: false
  
  application:
    name: APPOINTMENT-SERVICE


logging:
  level:
    '[org.hibernate]': DEBUG